# This is a basic workflow to help you get started with Actions

name: Armbian Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          repository: armbian/build
          ref: v20.08
          path: ./armbian-build

      # Runs a set of commands using the runners shell
      - name: Build Armbian
        run: |
          sudo apt-get -y install libfdt-dev
          ./armbian-build/compile.sh KERNEL_ONLY=no KERNEL_CONFIGURE=no BOARD=firefly-rk3399 BRANCH=current RELEASE=focal BUILD_DESKTOP=yes BUILD_MINIMAL=no

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Armbian_v20.08
          path: ./armbian-build/output/debug
